#Titulo que podré ver en la pestaña actions de mi repositorio
name: Mi Primer Workflow

#le digo a github que ejecute esto cada vez que alguien suba cambios
on:
  push:
    branches:
      - main

env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

jobs:
  saludo:
  #computadora temoiral en linux que me presta github
    runs-on: ubuntu-latest
    #tareas especificas, run me permite ejecutar insutrucciones de terminal como echo o date
    steps:
      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
        #este checkout me sirve para clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Listar directorio terraform
        run: ls -la
      - name: Mostrar directorio actual
        run: pwd
      - name: List terraform directory
        run: ls -la ./terraform
      - name: Initiate Terraform in terraform directory
        run: terraform init
        working-directory: terraform
      - name: Plan Terraform in terraform directory
        run: terraform plan
        working-directory: terraform
      - name: Apply Terraform in terraform directory
        run: terraform apply -auto-approve
        working-directory: terraform