#Titulo que podré ver en la pestaña actions de mi repositorio
name: Mi Primer Workflow

#le digo a github que ejecute esto cada vez que alguien suba cambios
on:
  push:
    branches:
      - main

jobs:
  saludo:
  #computadora temoiral en linux que me presta github
    runs-on: ubuntu-latest
    #tareas especificas, run me permite ejecutar insutrucciones de terminal como echo o date
    steps:
      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
